---
title: "An Introduction to docker4seq package"
author: "Raffaele A Calogero"
output: 
  BiocStyle::html_document
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction
The `r Githubpkg("kendomaniac/docker4seq")` package was developed to facilitate the use computing demamding steps in NGS data analysis.

The `r Githubpkg("kendomaniac/docker4seq")` package is the use of docker contaniers that embed demanding computing task as short reads mapping and counting. 
This approach provides multiple advantages: 
*user does not need to install all the software on its local server
*results generated by different containers can be organized in pipelines
*reproducibility is guarantee by the possibility of sharing the docker containers used for the analysis 

## Requirements
The minimal hardware requirements are a 4 core 64 bits linux computer with [docker](https://www.docker.com/) installed.
A folder with read/write permission for any users (chmod 777)

## Available workflows
At the present time are available the following workflows:


* mirnaCounts executes the workflow described in Cordero et al. PLoS One. 2012;7(2):e31630, which embeds the following steps:
    + trimming adapters with [cutadapt](http://cutadapt.readthedocs.io/en/stable/guide.html)
    + miRNAs mapping on [mirbase](http://www.mirbase.org/) hairpins using [SHRiMP](http://compbio.cs.toronto.edu/shrimp/)
    + quantification of mature miRNAs.
* rnaseqCounts, which allows:
    + adapter trimming with [skewer](https://github.com/relipmoc/skewer)
    + mapping with [STAR](https://github.com/alexdobin/STAR)
    + counting genes and isoforms with [RSEM](http://deweylab.github.io/RSEM/)
    + ENSEMBL gene annotation.
* chipseq, which allows:
    + peak calling using either MACS v 1.4 or SICER v 1.1
    + connection of the peak to the nearest gene available in the chosen UCSC genome release,
    + full annotation of the nearest gene.
    
    

  
    


